person:
  #  Boolean
  boss: true
  #  Date
  birth: 2019/12/9
  #  int
  age: 18
  #  String[] [篮球,足球]
  interests:
    - 篮球
    - 足球
    - 18
  # List<String> 横向List
  animal: [阿猫,阿狗]
  #  Map<String, Object>: 横向Map
  score: {english:80,math:90} # english: 80 math: 90
  #  Set<Double> 纵向Set
  salarys:
    - 9999.98
    - 9999.99
  #  对象Pet
  pet:
    {name: agou,weight: 99}
  #    name: 阿狗
  #    weight: 99.99
  #  Map<String, List<Pet>> 纵向Map
  allPets:
    sick: # 这是Map中的键
      - {name: 阿狗,weight: 99.99} #第一个sick宠物
      - name: 阿猫 # 第二个sick宠物
        weight: 88.88
      - name: 阿虫
        weight: 77.77
    health: # 这是Map中的键
      - {name: 阿花,weight: 199.99}
      - {name: 阿明,weight: 199.99}
  #   String
  user-name: zhangsan

#  单引号会将 \n作为字符串输出   双引号会将\n 作为换行输出
#  双引号不会转义，单引号会转义


#spring:
#  banner:
#    location：
#    image:
#      bitdepth: 4
#  cache:
#    type: redis
#    redis:
#      time-to-live: 11000
