spring:
  datasource:
    url: jdbc:mysql://123.57.92.107:3306/springboot2
    username: root
    password: N331150871
    driver-class-name: com.mysql.jdbc.Driver

#    手动创建连接池时,配置的监控,连接池设置:
#    filters: stat,wall
#    max-active: 10

  #利用官方 druid-starter 时需要配置的设置:
    druid:
      aop-patterns: com.atguigu.admin.*  #springbean监控 admin下的所有组件
      filters: stat,wall,slf4j  #所有开启的功能

      stat-view-servlet:  #监控页配置
  #开启stat-view
        enabled: true
  #设置账号密码
        login-username: admin
        login-password: admin
  #重置按钮
        resetEnable: false

      web-stat-filter:  #web监控
        enabled: true
        urlPattern: /*   #监控哪些请求
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'  #排除那些请求


      filter:
        stat: #sql监控  对上面filters里面的stat的详细配置
          slow-sql-millis: 1000 #超过1000ms的查询 定义为慢查询
          logSlowSql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false  #不允许删除
            update-allow: false  #更新操作被拦截


  #    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3

# 配置mybatis规则、使用MyBatisPlus则此项配置无效
mybatis:
#全局配置文件
#可以不写全局配置文件，所有全局配置文件的配置都放在configuration配置项中即可
#  config-location: classpath:mybatis/mybatis-config.xml
  #映射文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:  # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true #mybatis-plus中是默认驼峰的


#      redis:
#        host: r-bp1nc7reqesxisgxpipd.redis.rds.aliyuncs.com
#        port: 6379
#        password: lfy:Lfy123456
#        client-type: jedis
#        jedis:
#          pool:
#            max-active: 10
#      #    url: redis://lfy:Lfy123456@r-bp1nc7reqesxisgxpipd.redis.rds.aliyuncs.com:6379
#      #    lettuce:
#      #      pool:
#      #        max-active: 10
#      #        min-idle: 5
#
#
#

#      boot:
#        admin:
#          client:
#            url: http://localhost:8888
#            instance:
#              prefer-ip: true  #使用ip注册进来
#      application:
#        name: boot-05-web-admin
#
#
#
#

#
#
#    # management 是所有actuator的配置
#    # management.endpoint.端点名.xxxx  对某个端点的具体配置
#    management:
#      endpoints:
#        enabled-by-default: true  #默认开启所有监控端点  true
#        web:
#          exposure:
#            include: '*' # 以web方式暴露所有端点
#
#      endpoint:   #对某个端点的具体配置
#        health:
#          show-details: always
#          enabled: true
#
#        info:
#          enabled: true
#
#        beans:
#          enabled: true
#
#        metrics:
#          enabled: true
#
#    info:
#      appName: boot-admin
#      appVersion: 1.0.0
#      mavenProjectName: @project.artifactId@
#      mavenProjectVersion: @project.version@